### ISSUE TITLE
I got the repeat function to work!! I dont know where to post this so im posting it in issues tab.

### ISSUE THREAD

**Issue by Gwerbyn** [CodingTrain/Logo#1]
@shiffman I got the repeat command to work just fine!

https://gyazo.com/7d15dc0c9fb87f0231fa7bea55663f52
[Logo-master.zip](https://github.com/shiffman/Logo/files/2521181/Logo-master.zip)

Love the Coding Train!
And its AkiMC the guy who hacked your Mastodon bot!

**Comment by Gwerbyn** [comment]
Just added the submit button since it was crashing when you start to remove parts of the Logo code since the syntax is broken.

https://gyazo.com/26a9da80253d99c8d87092eb64d92783
[Logo-master.zip](https://github.com/shiffman/Logo/files/2521190/Logo-master.zip)

**Comment by jugendhacker** [comment]
You could leeave a pull request for this, because this way it's hard to merge...

**Comment by shiffman** [comment]
Thank you so much! This project now has it's own implementation in #24!
