### ISSUE TITLE
How to make a pull request?

### ISSUE THREAD

**Issue by daanbreur** [CodingTrain/Logo#18]
Haii There,
I want to make a pull request but i can't do it if i try it asked which branches to merge. And i can push normal to. How to fix it?
![image](https://user-images.githubusercontent.com/32175349/47932186-40b5fd80-ded1-11e8-8538-d854bb36d80d.png)
![image](https://user-images.githubusercontent.com/32175349/47932221-59261800-ded1-11e8-9e76-8df521be3aec.png)

**Comment by daanbreur** [comment]
Thanks it works

**Comment by shiffman** [comment]
Thank you @daanbreur for learning how to do this and all of your submissions! I hope you will continue to contribute! 🚂 🌈 ⭐️
