### ISSUE TITLE
Similar thing I wrote for a CS assignment

### ISSUE THREAD

**Issue by npetrangelo** [CodingTrain/Logo#25]
https://github.com/npetrangelo/ShapyTurtle

**Comment by npetrangelo** [comment]
It's written in Python and it's not the Logo syntax.
It uses the string as a sequential element and bootstraps the parse function with a multiplied input string to repeat.

**Comment by shiffman** [comment]
Thanks! You can add this to the Coding Train website if you like!

https://github.com/CodingTrain/website/wiki/Community-Contributions-Guide
