### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Logo#27]
Things that I'm looking for to be added to the README?

* [x] link to web demo
* [x] link to thecodingtrain.com challenge pages
* [x] link to information and history of Logo itself
* [x] link to YouTube videos
* [x] example Logo designs

**Comment by shiffman** [comment]
Should any of these go on the page itself or just in the README? Also, we should probably document all the Logo commands we are supporting somewhere?

**Comment by levistep32** [comment]
I think someone should document the supported commands somewhere, but for right now I've made a pull request for the 5 checkboxes you left at the top.

**Comment by shiffman** [comment]
I'm going to close this an open a new issue.

**Comment by shiffman** [comment]
Oh, and thank you @levistep32!!! ❤️
