### ISSUE TITLE
Degress and Radians callbacks 

### ISSUE THREAD

**Issue by AmrBarghouthi** [CodingTrain/Logo#50]
https://github.com/CodingTrain/Logo/blob/4ef832510536603e7649e7ddec4f55fa11966b18/commandList.js#L81
https://github.com/CodingTrain/Logo/blob/4ef832510536603e7649e7ddec4f55fa11966b18/commandList.js#L87
i think some this line 81 and 87 should be swaped just look at it

**Comment by shiffman** [comment]
Indeed that doesn't look right!

**Comment by Toyz** [comment]
Swapping these doesn't make sense as RADIANS is meant to set it to `2*math.Pi` where DEGREES set its to a fixed 360

**Comment by Toyz** [comment]
Fixed in #48

**Comment by shiffman** [comment]
All set thank you!
