### ISSUE TITLE
Master is broken right now

### ISSUE THREAD

**Issue by EyLuismi** [CodingTrain/Logo#54]
Hi! I have attempted to try the last changes and I think Master is broken. I have tried to fix it, but I have not time right now :(

I think it broke going from 8ac582cf1846b9400754429a555886a0f9f52ece (Fixes Bugs Of #41 (#53)) to 92891673b9324794c33b5377c0265d437b619359 (Testing args OOP way (#52))

**Comment by shiffman** [comment]
Yes I think both #55 and #56 address all the broken things!

**Comment by shiffman** [comment]
Should be working now, re-open if any new issues!
