### ISSUE TITLE
How to select which repeat code to merge?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Logo#7]
I woke up to many amazing pull requests this morning: #2, #3, #4, #5, #6.

What is the best way for me to select one to merge as well as honor others contributions? Should I just decide? Vote? Just do whatever @meiamsome says (this is my usual approach to coding)?

One idea I have is to merge them one at a time by order of submission. And let each subsequent pull request have a chance to refactor and improve?

**Comment by jamet-julien** [comment]
My level of English does not allow me to present my code correctly. But I try despite all;)
I use your method with a Command Object allowing more flexibility later and no regex.
The integration of the parser allows little change in the original code (sketch.js).
But the criterion for choosing a code is, in my opinion, to be able to understand it first and foremost. That said I want to have a return on my proposal elsewhere ( if it's possible ).

**Comment by DelSquared** [comment]
#10 implemented more functions so maybe it would be neat since you would have more in one pull?

**Comment by fabritsius** [comment]
New commands I added were actually "invented" by me (I had no idea Logo is an existing language and there is a specification), at the same time I don't see any ways it might be harmful. I tried to preserve "convenient" structure and style of Logo language.

**Comment by daanbreur** [comment]
Make a vote and  people ar not able to vote it self

**Comment by UnderKoen** [comment]
I have a implementation where i have been working on for a couple months (in java).

**Comment by shiffman** [comment]
I ended up just doing my own  in #24!
